const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = await hre.ethers.provider.getNetwork();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Network:", hre.network.name);
  console.log("Chain ID:", network.chainId.toString());

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Balance:", hre.ethers.formatEther(balance), "ETH");
  if (balance === 0n) {
    console.error("ERROR: Deployer has no ETH. Fund the account first.");
    process.exit(1);
  }

  const reputationRegistryAddress = process.env.REPUTATION_REGISTRY_ADDRESS || "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63";
  const platformFeeRate = parseInt(process.env.PLATFORM_FEE_RATE || "250"); // 2.5%

  const deployed = {};

  console.log("\n=== Phase 1: Core Contracts ===\n");

  console.log("--- Deploying ClawTrustRepAdapter ---");
  const ClawTrustRepAdapter = await hre.ethers.getContractFactory("ClawTrustRepAdapter");
  const repAdapter = await ClawTrustRepAdapter.deploy(reputationRegistryAddress);
  await repAdapter.waitForDeployment();
  deployed.repAdapter = await repAdapter.getAddress();
  console.log("ClawTrustRepAdapter deployed to:", deployed.repAdapter);

  console.log("\n--- Deploying ClawTrustSwarmValidator ---");
  const ClawTrustSwarmValidator = await hre.ethers.getContractFactory("ClawTrustSwarmValidator");
  const swarmValidator = await ClawTrustSwarmValidator.deploy();
  await swarmValidator.waitForDeployment();
  deployed.swarmValidator = await swarmValidator.getAddress();
  console.log("ClawTrustSwarmValidator deployed to:", deployed.swarmValidator);

  console.log("\n--- Deploying ClawTrustEscrow ---");
  const ClawTrustEscrow = await hre.ethers.getContractFactory("ClawTrustEscrow");
  const escrow = await ClawTrustEscrow.deploy(deployed.swarmValidator, platformFeeRate);
  await escrow.waitForDeployment();
  deployed.escrow = await escrow.getAddress();
  console.log("ClawTrustEscrow deployed to:", deployed.escrow);

  console.log("\n--- Deploying ClawCardNFT ---");
  const ClawCardNFT = await hre.ethers.getContractFactory("ClawCardNFT");
  const clawCard = await ClawCardNFT.deploy();
  await clawCard.waitForDeployment();
  deployed.clawCardNFT = await clawCard.getAddress();
  console.log("ClawCardNFT deployed to:", deployed.clawCardNFT);

  console.log("\n=== Phase 2: Configuration ===\n");

  console.log("[RepAdapter] Authorizing deployer as oracle...");
  const isOracle = await repAdapter.authorizedOracles(deployer.address);
  console.log("[RepAdapter] Deployer already oracle:", isOracle);

  console.log("[RepAdapter] Testing computeFusedScore(890, 4200)...");
  const testFused = await repAdapter.computeFusedScore(890, 4200);
  console.log("[RepAdapter] computeFusedScore result:", testFused.toString(), "(expected ~70)");

  console.log("\n=== Phase 3: Smoke Tests ===\n");

  try {
    const testTags = ["audit", "security"];
    const testProof = "ipfs://clawtrust/test/proof.json";
    const tx = await repAdapter.submitFusedFeedback(deployer.address, 890, 4200, testTags, testProof);
    const receipt = await tx.wait();
    console.log("[RepAdapter] submitFusedFeedback tx:", receipt.hash);

    const fusedResult = await repAdapter.getFusedScore(deployer.address);
    console.log("[RepAdapter] Stored fused score:", {
      onChainScore: fusedResult.onChainScore.toString(),
      moltbookKarma: fusedResult.moltbookKarma.toString(),
      fusedScore: fusedResult.fusedScore.toString(),
    });
  } catch (err) {
    console.log("[RepAdapter] Smoke test skipped:", err.message?.substring(0, 100));
  }

  console.log("\n=== Phase 4: Generate Config ===\n");

  const addressConfig = {
    network: hre.network.name,
    chainId: network.chainId.toString(),
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      ClawTrustEscrow: deployed.escrow,
      ClawTrustRepAdapter: deployed.repAdapter,
      ClawTrustSwarmValidator: deployed.swarmValidator,
      ClawCardNFT: deployed.clawCardNFT,
      ReputationRegistry: reputationRegistryAddress,
    },
    platformFeeRate: platformFeeRate / 100 + "%",
  };

  const addressesPath = path.join(__dirname, "..", "deployed-addresses.json");
  fs.writeFileSync(addressesPath, JSON.stringify(addressConfig, null, 2));
  console.log("Contract addresses saved to:", addressesPath);

  const chainClientUpdate = `
// Auto-generated by deploy.cjs on ${new Date().toISOString()}
// Network: ${hre.network.name} (Chain ID: ${network.chainId})
// Update server/chain-client.ts with these values:
//
// ESCROW_ADDRESS = "${deployed.escrow}"
// REP_ADAPTER_ADDRESS = "${deployed.repAdapter}"
// SWARM_VALIDATOR_ADDRESS = "${deployed.swarmValidator}"
// CLAW_CARD_NFT_ADDRESS = "${deployed.clawCardNFT}"
`;
  console.log(chainClientUpdate);

  console.log("=== Deployment Summary ===");
  console.log(JSON.stringify(addressConfig.contracts, null, 2));

  console.log("\n=== Post-Deployment Checklist ===");
  console.log("1. Update server/chain-client.ts with deployed addresses above");
  console.log("2. Authorize backend oracle wallet:", `repAdapter.authorizeOracle(<backend_wallet>)`);
  console.log("3. Verify contracts on BaseScan:");
  console.log(`   npx hardhat verify --network baseSepolia ${deployed.escrow} ${deployed.swarmValidator} ${platformFeeRate}`);
  console.log(`   npx hardhat verify --network baseSepolia ${deployed.repAdapter} ${reputationRegistryAddress}`);
  console.log(`   npx hardhat verify --network baseSepolia ${deployed.swarmValidator}`);
  console.log(`   npx hardhat verify --network baseSepolia ${deployed.clawCardNFT}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
